# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AppSkelton.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(800, 600)
        # mainWindow.setStyleSheet("background-color:\"grey\";")
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuImage_Grid = QtWidgets.QMenu(self.menuView)
        self.menuImage_Grid.setObjectName("menuImage_Grid")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuProject = QtWidgets.QMenu(self.menubar)
        self.menuProject.setObjectName("menuProject")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(mainWindow)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolBar.setObjectName("toolBar")
        mainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionNew = QtWidgets.QAction(mainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionQuit = QtWidgets.QAction(mainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionGenerateXML = QtWidgets.QAction(mainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Resources/Images/run.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGenerateXML.setIcon(icon)
        self.actionGenerateXML.setObjectName("actionGenerateXML")
        self.actionConnectCmpts = QtWidgets.QAction(mainWindow)
        self.actionConnectCmpts.setEnabled(False)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Resources/Images/connect.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConnectCmpts.setIcon(icon1)
        self.actionConnectCmpts.setObjectName("actionConnectCmpts")
        self.actionShow_Results = QtWidgets.QAction(mainWindow)
        self.actionShow_Results.setObjectName("actionShow_Results")
        self.action5_images_per_row = QtWidgets.QAction(mainWindow)
        self.action5_images_per_row.setCheckable(True)
        self.action5_images_per_row.setObjectName("action5_images_per_row")
        self.action7_images_per_row = QtWidgets.QAction(mainWindow)
        self.action7_images_per_row.setCheckable(True)
        self.action7_images_per_row.setChecked(True)
        self.action7_images_per_row.setObjectName("action7_images_per_row")
        self.action3_images_per_row = QtWidgets.QAction(mainWindow)
        self.action3_images_per_row.setCheckable(True)
        self.action3_images_per_row.setObjectName("action3_images_per_row")
        self.actionCoustom = QtWidgets.QAction(mainWindow)
        self.actionCoustom.setCheckable(True)
        self.actionCoustom.setObjectName("actionCoustom")
        self.actionUpdateCmpts = QtWidgets.QAction(mainWindow)
        self.actionUpdateCmpts.setEnabled(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Resources/Images/update.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUpdateCmpts.setIcon(icon2)
        self.actionUpdateCmpts.setObjectName("actionUpdateCmpts")
        self.actionFinish = QtWidgets.QAction(mainWindow)
        self.actionFinish.setEnabled(False)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Resources/Images/finish.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFinish.setIcon(icon3)
        self.actionFinish.setObjectName("actionFinish")
        self.actionView_Doccument = QtWidgets.QAction(mainWindow)
        self.actionView_Doccument.setObjectName("actionView_Doccument")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuImage_Grid.addSeparator()
        self.menuImage_Grid.addAction(self.action3_images_per_row)
        self.menuImage_Grid.addAction(self.action5_images_per_row)
        self.menuImage_Grid.addAction(self.action7_images_per_row)
        self.menuImage_Grid.addAction(self.actionCoustom)
        self.menuView.addAction(self.menuImage_Grid.menuAction())
        self.menuHelp.addAction(self.actionView_Doccument)
        self.menuProject.addAction(self.actionGenerateXML)
        self.menuProject.addAction(self.actionUpdateCmpts)
        self.menuProject.addAction(self.actionConnectCmpts)
        self.menuProject.addAction(self.actionFinish)
        self.menuProject.addSeparator()
        self.menuProject.addAction(self.actionShow_Results)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuProject.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionGenerateXML)
        self.toolBar.addAction(self.actionUpdateCmpts)
        self.toolBar.addAction(self.actionConnectCmpts)
        self.toolBar.addAction(self.actionFinish)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "MainWindow"))
        self.menuFile.setTitle(_translate("mainWindow", "File"))
        self.menuView.setTitle(_translate("mainWindow", "View"))
        self.menuImage_Grid.setTitle(_translate("mainWindow", "Image Grid"))
        self.menuHelp.setTitle(_translate("mainWindow", "Help"))
        self.menuProject.setTitle(_translate("mainWindow", "Run"))
        self.toolBar.setWindowTitle(_translate("mainWindow", "toolBar"))
        self.actionNew.setText(_translate("mainWindow", "New"))
        self.actionNew.setShortcut(_translate("mainWindow", "Ctrl+N"))
        self.actionQuit.setText(_translate("mainWindow", "Quit"))
        self.actionGenerateXML.setText(_translate("mainWindow", "Generate XML"))
        self.actionGenerateXML.setShortcut(_translate("mainWindow", "F5"))
        self.actionConnectCmpts.setText(_translate("mainWindow", "Connect"))
        self.actionConnectCmpts.setShortcut(_translate("mainWindow", "F7"))
        self.actionShow_Results.setText(_translate("mainWindow", "Show Results"))
        self.actionShow_Results.setShortcut(_translate("mainWindow", "Ctrl+R"))
        self.action5_images_per_row.setText(_translate("mainWindow", "5 images per row"))
        self.action7_images_per_row.setText(_translate("mainWindow", "7 images per row "))
        self.action3_images_per_row.setText(_translate("mainWindow", "3 images per row "))
        self.actionCoustom.setText(_translate("mainWindow", "Coustom..."))
        self.actionUpdateCmpts.setText(_translate("mainWindow", "Update Components"))
        self.actionUpdateCmpts.setShortcut(_translate("mainWindow", "F6"))
        self.actionFinish.setText(_translate("mainWindow", "Finish"))
        self.actionFinish.setShortcut(_translate("mainWindow", "F8"))
        self.actionView_Doccument.setText(_translate("mainWindow", "View Doccument"))
        self.actionGenerateXML.setEnabled(False)
        self.actionConnectCmpts.setEnabled(False)
        self.actionUpdateCmpts.setEnabled(False)


#import icons_rc
