# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'try.ui'
#
# Created: Sun Mar  3 05:57:37 2019
#      by: PyQt4 UI code generator 4.11.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName(_fromUtf8("mainWindow"))
        mainWindow.resize(800, 600)
        mainWindow.setAcceptDrops(True)
        self.centralwidget = QtGui.QWidget(mainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuRecent_projects = QtGui.QMenu(self.menuFile)
        self.menuRecent_projects.setObjectName(_fromUtf8("menuRecent_projects"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuImage_Grid = QtGui.QMenu(self.menuView)
        self.menuImage_Grid.setObjectName(_fromUtf8("menuImage_Grid"))
        self.menuSettings = QtGui.QMenu(self.menubar)
        self.menuSettings.setObjectName(_fromUtf8("menuSettings"))
        self.menuWindow = QtGui.QMenu(self.menubar)
        self.menuWindow.setObjectName(_fromUtf8("menuWindow"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuProject = QtGui.QMenu(self.menubar)
        self.menuProject.setObjectName(_fromUtf8("menuProject"))
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(mainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        mainWindow.setStatusBar(self.statusbar)
        self.dockDesign = QtGui.QDockWidget(mainWindow)
        self.dockDesign.setObjectName(_fromUtf8("dockDesign"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.dockDesign.setWidget(self.dockWidgetContents)
        mainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockDesign)
        self.dockPictuers = QtGui.QDockWidget(mainWindow)
        self.dockPictuers.setObjectName(_fromUtf8("dockPictuers"))
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName(_fromUtf8("dockWidgetContents_2"))
        self.treeView = QtGui.QTreeView(self.dockWidgetContents_2)
        #self.treeView.setGeometry(QtCore.QRect(-20, 80, 256, 192))
        self.treeView.setObjectName(_fromUtf8("treeView"))
        self.dockPictuers.setWidget(self.dockWidgetContents_2)
        mainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockPictuers)
        self.actionNew = QtGui.QAction(mainWindow)
        self.actionNew.setObjectName(_fromUtf8("actionNew"))
        self.actionOpen = QtGui.QAction(mainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.action1 = QtGui.QAction(mainWindow)
        self.action1.setObjectName(_fromUtf8("action1"))
        self.action2 = QtGui.QAction(mainWindow)
        self.action2.setObjectName(_fromUtf8("action2"))
        self.actionSave = QtGui.QAction(mainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionSave_as = QtGui.QAction(mainWindow)
        self.actionSave_as.setObjectName(_fromUtf8("actionSave_as"))
        self.actionClose = QtGui.QAction(mainWindow)
        self.actionClose.setObjectName(_fromUtf8("actionClose"))
        self.actionQuit = QtGui.QAction(mainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionUndo = QtGui.QAction(mainWindow)
        self.actionUndo.setObjectName(_fromUtf8("actionUndo"))
        self.actionRedo = QtGui.QAction(mainWindow)
        self.actionRedo.setObjectName(_fromUtf8("actionRedo"))
        self.actionCopy = QtGui.QAction(mainWindow)
        self.actionCopy.setObjectName(_fromUtf8("actionCopy"))
        self.actionCut = QtGui.QAction(mainWindow)
        self.actionCut.setObjectName(_fromUtf8("actionCut"))
        self.actionPaste = QtGui.QAction(mainWindow)
        self.actionPaste.setObjectName(_fromUtf8("actionPaste"))
        self.actionSelect_All = QtGui.QAction(mainWindow)
        self.actionSelect_All.setObjectName(_fromUtf8("actionSelect_All"))
        self.actionPictuers = QtGui.QAction(mainWindow)
        self.actionPictuers.setCheckable(True)
        self.actionPictuers.setChecked(True)
        self.actionPictuers.setObjectName(_fromUtf8("actionPictuers"))
        self.actionDesign_output = QtGui.QAction(mainWindow)
        self.actionDesign_output.setCheckable(True)
        self.actionDesign_output.setChecked(True)
        self.actionDesign_output.setObjectName(_fromUtf8("actionDesign_output"))
        self.actionDesign_Code = QtGui.QAction(mainWindow)
        self.actionDesign_Code.setCheckable(True)
        self.actionDesign_Code.setChecked(True)
        self.actionDesign_Code.setObjectName(_fromUtf8("actionDesign_Code"))
        self.actionRun = QtGui.QAction(mainWindow)
        self.actionRun.setObjectName(_fromUtf8("actionRun"))
        self.actionEdit_Configurations = QtGui.QAction(mainWindow)
        self.actionEdit_Configurations.setObjectName(_fromUtf8("actionEdit_Configurations"))
        self.actionStop = QtGui.QAction(mainWindow)
        self.actionStop.setObjectName(_fromUtf8("actionStop"))
        self.actionShow_Results = QtGui.QAction(mainWindow)
        self.actionShow_Results.setObjectName(_fromUtf8("actionShow_Results"))
        self.action5_images_per_row = QtGui.QAction(mainWindow)
        self.action5_images_per_row.setObjectName(_fromUtf8("action5_images_per_row"))
        self.action7_images_per_row = QtGui.QAction(mainWindow)
        self.action7_images_per_row.setObjectName(_fromUtf8("action7_images_per_row"))
        self.action3_images_per_row = QtGui.QAction(mainWindow)
        self.action3_images_per_row.setObjectName(_fromUtf8("action3_images_per_row"))
        self.actionCoustom = QtGui.QAction(mainWindow)
        self.actionCoustom.setObjectName(_fromUtf8("actionCoustom"))
        self.menuRecent_projects.addAction(self.action1)
        self.menuRecent_projects.addAction(self.action2)
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.menuRecent_projects.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addAction(self.actionSelect_All)
        self.menuImage_Grid.addSeparator()
        self.menuImage_Grid.addAction(self.action3_images_per_row)
        self.menuImage_Grid.addAction(self.action5_images_per_row)
        self.menuImage_Grid.addAction(self.action7_images_per_row)
        self.menuImage_Grid.addAction(self.actionCoustom)
        self.menuView.addAction(self.actionPictuers)
        self.menuView.addAction(self.actionDesign_output)
        self.menuView.addAction(self.actionDesign_Code)
        self.menuView.addAction(self.menuImage_Grid.menuAction())
        self.menuProject.addAction(self.actionRun)
        self.menuProject.addAction(self.actionEdit_Configurations)
        self.menuProject.addAction(self.actionStop)
        self.menuProject.addAction(self.actionShow_Results)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuProject.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        mainWindow.setWindowTitle(_translate("mainWindow", "MainWindow", None))
        self.menuFile.setTitle(_translate("mainWindow", "File", None))
        self.menuRecent_projects.setTitle(_translate("mainWindow", "Recent projects", None))
        self.menuEdit.setTitle(_translate("mainWindow", "Edit", None))
        self.menuView.setTitle(_translate("mainWindow", "View", None))
        self.menuImage_Grid.setTitle(_translate("mainWindow", "Image Grid", None))
        self.menuSettings.setTitle(_translate("mainWindow", "Settings", None))
        self.menuWindow.setTitle(_translate("mainWindow", "Window", None))
        self.menuHelp.setTitle(_translate("mainWindow", "Help", None))
        self.menuProject.setTitle(_translate("mainWindow", "Run", None))
        self.dockDesign.setWindowTitle(_translate("mainWindow", "Design", None))
        self.dockPictuers.setWindowTitle(_translate("mainWindow", "Project", None))
        self.actionNew.setText(_translate("mainWindow", "New", None))
        self.actionNew.setShortcut(_translate("mainWindow", "Ctrl+N", None))
        self.actionOpen.setText(_translate("mainWindow", "Open", None))
        self.actionOpen.setShortcut(_translate("mainWindow", "Ctrl+O", None))
        self.action1.setText(_translate("mainWindow", "1.", None))
        self.action2.setText(_translate("mainWindow", "2.", None))
        self.actionSave.setText(_translate("mainWindow", "Save", None))
        self.actionSave.setShortcut(_translate("mainWindow", "Ctrl+S", None))
        self.actionSave_as.setText(_translate("mainWindow", "Save As...", None))
        self.actionSave_as.setShortcut(_translate("mainWindow", "Ctrl+Shift+S", None))
        self.actionClose.setText(_translate("mainWindow", "Close", None))
        self.actionClose.setShortcut(_translate("mainWindow", "Ctrl+Alt+F4", None))
        self.actionQuit.setText(_translate("mainWindow", "Quit", None))
        self.actionUndo.setText(_translate("mainWindow", "Undo", None))
        self.actionUndo.setShortcut(_translate("mainWindow", "Ctrl+Z", None))
        self.actionRedo.setText(_translate("mainWindow", "Redo", None))
        self.actionRedo.setShortcut(_translate("mainWindow", "Ctrl+Shift+Z", None))
        self.actionCopy.setText(_translate("mainWindow", "Copy", None))
        self.actionCopy.setShortcut(_translate("mainWindow", "Ctrl+C", None))
        self.actionCut.setText(_translate("mainWindow", "Cut", None))
        self.actionCut.setShortcut(_translate("mainWindow", "Ctrl+X", None))
        self.actionPaste.setText(_translate("mainWindow", "Paste", None))
        self.actionPaste.setShortcut(_translate("mainWindow", "Ctrl+V", None))
        self.actionSelect_All.setText(_translate("mainWindow", "Select All ", None))
        self.actionSelect_All.setShortcut(_translate("mainWindow", "Ctrl+Shift+A", None))
        self.actionPictuers.setText(_translate("mainWindow", "Pictuers ", None))
        self.actionDesign_output.setText(_translate("mainWindow", "Design output", None))
        self.actionDesign_Code.setText(_translate("mainWindow", "Design Code", None))
        self.actionRun.setText(_translate("mainWindow", "Run", None))
        self.actionRun.setShortcut(_translate("mainWindow", "F5", None))
        self.actionEdit_Configurations.setText(_translate("mainWindow", "Edit Configurations..", None))
        self.actionStop.setText(_translate("mainWindow", "Stop", None))
        self.actionStop.setShortcut(_translate("mainWindow", "Shift+F5", None))
        self.actionShow_Results.setText(_translate("mainWindow", "Show Results", None))
        self.actionShow_Results.setShortcut(_translate("mainWindow", "Ctrl+R", None))
        self.action5_images_per_row.setText(_translate("mainWindow", "5 images per row", None))
        self.action7_images_per_row.setText(_translate("mainWindow", "7 images per row ", None))
        self.action3_images_per_row.setText(_translate("mainWindow", "3 images per row ", None))
        self.actionCoustom.setText(_translate("mainWindow", "Coustom...", None))

